### ISSUE TITLE
Refactor printing out of main function

### ISSUE THREAD

**Issue by carlbordum** [carlbordum/manly#10]
It would be neat if the printing could be refactored out of `main`[1] and into the `if __name__ == "__main__"` condition. I dont know exactly what `main` should return. Probably just a list of strings. Ideas?

[1] https://github.com/carlbordum/manly/blob/master/manly.py#L128

**Comment by vishal-wadhwa** [comment]
If you want to move the _printing_ part out of main to `if __name__ == "__main__"` condition, then, main should return `title` and `output`. I can do this for you. Should I proceed?

**Comment by carlbordum** [comment]
That makes sense. You're welcome to implement this!

**Comment by vishal-wadhwa** [comment]
Added a fix in PR #11
