### ISSUE TITLE
Supress some output from subprocess

### ISSUE THREAD

**Issue by carlbordum** [carlbordum/manly#6]
Output from commands like `manly gcc -Wformat` should be supressed.

Im talking about
```
<standard input>:10037: warning [p 110, 10.5i]: can't break line
<standard input>:10067: warning [p 110, 15.3i]: can't break line
<standard input>:10301: warning [p 113, 1.2i]: can't break line
<standard input>:14825: warning [p 149, 0.7i]: can't break line
```

**Comment by mpolidori** [comment]
Sorry for the duplicate references. Still getting the hang of this.

**Comment by mpolidori** [comment]
The solution for issue #15 solved the "can't break line" errors for me. The code I worked on changed since I cloned the project and the problem seems fixed now. I'm not sure if I'm supposed to delete my commit or not.

**Comment by carlbordum** [comment]
Hey mpolidori,

I decided to go with #15 to solve this issue. You don't have to delete commits or anything.

Thank you very much for your interest in the project :)

Ask if theres anything you think I can help with and Ill do my best

**Comment by mpolidori** [comment]
@carlbordum That's understandable. It's a better solution. 

I just discovered this project, and it'll definitely be a staple on all of my future setups!

Thanks, I really appreciate it.
